version: '3.6'
services:
  app:
    build:
      context: server/
      dockerfile: .
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/srv:cached
    working_dir: /srv
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: "db"
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/settings/:/docker-entrypoint-initdb.d
    - ./mysql/data/:/var/lib/mysql
    - ./mysql/settings/setting.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: "sample"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
      TZ: "Asia/Tokyo"